# Generated by Django 3.0.8 on 2020-11-07 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('color', models.CharField(choices=[('#f33', 'Rojo'), ('#5f33ff', 'Azul'), ('#ffd333', 'Amarillo'), ('#ff7e33', 'Anaranjado'), ('#a3f', 'Morado'), ('#3aff33', 'Verde')], default='Azul', max_length=20, verbose_name='Color de Evento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('start_time', models.DateTimeField(verbose_name='Comienzo de Evento')),
                ('end_time', models.DateTimeField(verbose_name='Final de Evento')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo de Evento')),
                ('color', models.CharField(max_length=20, verbose_name='Color de Evento')),
            ],
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('adults', models.IntegerField(default=0, verbose_name='Adultos')),
                ('kids', models.IntegerField(default=0, verbose_name='Niños')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='tipo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.TypeEvents'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
